### ISSUE TITLE
PyTorch API incompatibility (at::zeros())) with pytorch 1.0.0 (unique_kernel.cu)

### ISSUE THREAD

**Issue by Twittadrock** [rusty1s/pytorch_unique#8]
I think I noticed an API incompatibility with `pytorch's at::zeros()` function with PyTorch 1.0.
They must have changed the function argument at some time.

Error in unique_kernel.cu, line 22:
`auto mask = at::zeros(src.type().toScalarType(at::kByte), {src.numel()});`

I needed to change the order of arguments: 
`auto mask = at::zeros({src.numel()}, src.type().toScalarType(at::kByte));`

Still not exactly sure if my installation is using the unqiue_kernel. Do you know a way to verify this? 

Best regards,
Matthias

**Comment by rusty1s** [comment]
Hi,
I won't update PyTorch Unique for PyTorch 1.0, because PyTorch now has its own `unique` implementation. Therefore, this version is fixed for people who are forced to develop on earlier PyTorch versions.

Your installation will definitively use the unique kernel if your input lies on the GPU. You can add print statements to the *.cu files for verification.

**Comment by Twittadrock** [comment]
Makes sense. Thanks for the quick reply.
